version: "3.2"
services:
  php-data-mapper:
    container_name: php-apache
    image: php
    build:
      context: .docker
    volumes:
      - ./:/var/www/html/
    ports:
      - "8082:80"
    environment:
      APACHE_RUN_USER: '#1000'
